### PR TITLE
Update 1.0.11

### PR DESCRIPTION
**Pull request by QuoterMusic**
**Behavior**
- Add Static Popup Label (with and without Close Button)

**Marker Title**
- Add Title Alignment Option

**New Free Map Tiles**
- Add Stamen Toner
- Add Stamen Terrain
- Add Stamen Watercolor

**GDPR Support**
The plugin supports Tiles Proxy for OpenStreetMap
You only need to set the Tiles (caching) url as Custom Map Tile URL. 
The CSS and JS files are not needed as they are already included in OSM Map Widget for Elementor.

### CODE REVIEW

**Comment by flopperj** [comment]
@QuoterMusic - Great additions, thank you for your contributions!

**Comment by flopperj** [comment]
@QuoterMusic - Hey I was able to add you as a contributor to the Wordpress plugin. You should now have access to pull and commit any new changes. However, I'd love it if we still submitted PRs against the github repo so we're able to review each others code and that we always have the updated source on here.

One thing I noticed before I committed your changes is that the version was not updated [here](https://github.com/QuoterMusic/osm-map-elementor/blob/ec050239de4d27ee185bdfca6bcac17966caf981/osm-map-elementor.php#L7).

Please fetch latest from my main branch. I also added a few minor tweaks that are not in your branch.

Cheers!

**Comment by QuoterMusic** [comment]
@flopperj 
Okay I have turned on the Synchronisation in my fork I had probably forgotten sorry.

And I don't know who garbowza is but he was on [wordpress.org](https://wordpress.org/plugins/osm-map-elementor) as Contributors & Developers so I took him over.

I received a message but did not see any changes in my account on Wordpress.org. 
But I was planning to continue making pull requests anyway.

Cheers!

**Comment by flopperj** [comment]
Excellent, garbowza is the owner of the plugin and was the original creator before I came in :) 

To start committing / making changes to the LIVE plugin please [read this](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/). Wordpress uses SVN which at times can be confusing.

**Pull request merged**
