### PR TITLE
Update 1.2.1

### PR DESCRIPTION
**Pull request by QuoterMusic**
- Remove Deprecated code @rami-elementor
- Remove all Deprecated Code Comments @QuoterMusic

### CODE REVIEW

**Comment by QuoterMusic** [comment]
@flopperj 

It would be great if you could check again if everything works for you and then merge it directly.

And then I would publish the update 1.2.1 on wordpress.org during the day.

**Comment by flopperj** [comment]
Sweet! Thanks for doing this cleanup.

Just noticed that the **Open Street Map** link in the wordpress readme file is not pointing to the about page. Mind updating that  link within this PR?
https://github.com/flopperj/osm-map-elementor/blob/2eed67a3969b5f9e5fe45209b82054c8c02289a0/readme.txt#L16

To point to: https://www.openstreetmap.org/about

**Comment by flopperj** [comment]
@QuoterMusic Thanks for doing this cleanup.

Just noticed that the **Open Street Map** link in the wordpress readme file is not pointing to the about page. Mind updating that  link within this PR?
https://github.com/flopperj/osm-map-elementor/blob/2eed67a3969b5f9e5fe45209b82054c8c02289a0/readme.txt#L16

To point to: https://www.openstreetmap.org/about

Other than that your changes still work as expected in my local test environment.

**Comment by QuoterMusic** [comment]
@flopperj

Thank you at the point I forgot I have adjusted it.

**Review by flopperj — APPROVED** [review]
LGTM! ✅

**Pull request merged**
