### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by QuoterMusic**
fix OpenStreetMap License

### CODE REVIEW

**Comment by QuoterMusic** [comment]
I just thought wrong and replaced OSM above with https://www.openstreetmap.org/about 

and added below Under License https://www.openstreetmap.org/copyright

Unfortunately, however, was missing an enter sry

**Review by flopperj — APPROVED** [review]
Good catch! LGTM ✅

**Comment by flopperj** [comment]
Feel free to merge this when ready 😃

**Comment by QuoterMusic** [comment]
@flopperj 
Should I then update the plugin on wordpress.org or do you do that ? I could do that only in a few hours after sleeping.
And you would have to adjust in the about tab the Requires Elementor plugin version to 3.5
And as I said you could add the wordpress.org plugin link.

**Comment by flopperj** [comment]
@QuoterMusic Please do! Would be appreciated. Thanks again for all your contributions 🙏🏿

**Comment by flopperj** [comment]
Updated the About tab as well. Good call out.

**Pull request merged**
